import { openApp, mkSave } from './_critic2-lib.mjs';
const save = mkSave({ expedition: { tiers: {}, progress: { bridges: 3, picnic: 3, raft: 3 } } });
const { browser, page, errors } = await openApp({ width: 1024, height: 768 }, save);
await page.evaluate(() => window.BooTown.go('expeditionpuzzle', { node: 'hotel' }));
await page.waitForSelector('.exp-puzzle .exp-puzzle-board button');
await page.evaluate(async () => { for (let i = 0; i < 8; i++) { window.__expeditionPuzzle.try(i); await new Promise(r => setTimeout(r, 100)); } });
await page.waitForTimeout(2000);
await page.click('.exp-postcard-done');
await page.waitForTimeout(3000);
console.log('after Done +3s, localStorage care:', await page.evaluate(() => localStorage.getItem('bootown.save.v1').match(/"care":\{[^}]*\}[^}]*\}/)?.[0]));
await page.reload();
await page.waitForSelector('.hub');
const after = await page.evaluate(async () => { const st = await import('/js/state.js'); return JSON.parse(JSON.stringify(st.getState().care || {})); });
console.log('care AFTER RELOAD:', JSON.stringify(after));
console.log('expedition AFTER RELOAD:', await page.evaluate(async () => { const st = await import('/js/state.js'); return JSON.stringify(st.getState().expedition); }));
console.log('errors:', errors.length ? errors : 'none');
await browser.close();
