// tests/lib/run15_balance.mjs — RUN15 V5: the balance simulation.
// Runs 30 days of play at three profiles against the REAL award machinery
// (js/comfort.js's spendableAward + data/startypes.js's mapping) and the REAL price
// table, and reports what each can afford at days 7, 14 and 30.
// Writes tests/run15_balance.md. Node-direct: no browser, no DOM.
import { writeFileSync } from 'fs';
import { SHELVES, priceOf, WELCOME_PURSE } from '../../data/shop.js';
import { spendableAward, levelMultiplier } from '../../js/comfort.js';
import { starTypeFor, TYPE_KEYS } from '../../data/startypes.js';

// ---- the three profiles, as RUN15 V5 names them --------------------------------------
// Each is a day's play: a list of rounds {game, cat, level, stars, above}.
// "above" = the round was above her comfort level (the Brave case).
const R = (game, cat, level, stars, above = false) => ({ game, cat, level, stars, above });
const PROFILES = {
  farmer: {
    label: 'Maths-only farmer',
    note: 'Six Bubble Pop rounds a day at Level 1, three stars each. Never strays.',
    day: () => Array.from({ length: 6 }, () => R('bubblepop', 'tables', 1, 3))
  },
  broad: {
    label: 'Broad player',
    note: 'Five rounds a day across maths, words, puzzles and making things, mostly Level 2 with a stretch — and a lesson every third day, because breadth includes lessons.',
    day: (d) => [
      R('bubblepop', 'tables', 2, 3),
      R('spellboo', 'spell', 2, 2),
      R('oddboo', null, 2, 3),
      d % 3 === 0 ? R('teachme', null, null, 3) : R('paint', null, null, 3),
      d % 3 === 0 ? R('booroll', null, 3, 2, true) : R('clockshop', 'clock', 2, 3)
    ]
  },
  lessons: {
    label: 'Lesson-keen player',
    note: 'A lesson most days plus three ordinary rounds — the profile the Special shelf is for.',
    day: (d) => [
      d % 4 !== 3 ? R('teachme', null, null, 3) : R('teachme', null, null, 2),
      R('bubblepop', 'tables', 2, 3),
      R('spellboo', 'spell', 1, 3),
      R('oddboo', null, 2, 2)
    ]
  }
};
// A lesson she has already aced pays the cosy award — V3.3's un-farmable recap.
const RECAP_AFTER = 6;          // lessons that exist today (data/lessons.js); RUN16 adds more
const RECAP_STARS = 1;          // a recap credits its cosy award, never the full three

function runProfile(name, days = 30) {
  const p = PROFILES[name];
  const wallet = Object.fromEntries([...TYPE_KEYS, 'legacy'].map(k => [k, 0]));
  wallet.legacy = WELCOME_PURSE;        // the Welcome purse, day one
  const timeline = {};
  let lessonsDone = 0;
  for (let d = 1; d <= days; d++) {
    for (const r of p.day(d)) {
      let stars = r.stars, level = r.level;
      if (r.game === 'teachme') {
        lessonsDone++;
        if (lessonsDone > RECAP_AFTER) stars = RECAP_STARS;   // recaps are capped
      }
      const award = spendableAward({ stars, level, above: r.above });
      wallet[starTypeFor(r.game, r.cat)] += award.spendable;
    }
    if (d === 7 || d === 14 || d === 30) timeline[d] = { ...wallet };
  }
  return timeline;
}

// What a wallet can afford on each shelf: how many items, and the dearest one.
function affordability(wallet) {
  const out = {};
  for (const shelf of SHELVES) {
    const purse = (wallet[shelf.currency] || 0) + (wallet.legacy || 0);
    const affordable = shelf.items.filter(([, cost]) => cost <= purse);
    const dearest = affordable.length ? Math.max(...affordable.map(([, c]) => c)) : 0;
    out[shelf.id] = { purse, count: affordable.length, of: shelf.items.length, dearest };
  }
  return out;
}
// A more honest question than "can she afford the dearest item": how much can she
// actually BUY, spending greedily cheapest-first within one shelf's currency?
function basket(wallet, shelfId) {
  const shelf = SHELVES.find(s => s.id === shelfId);
  let purse = (wallet[shelf.currency] || 0) + (wallet.legacy || 0);
  const sorted = [...shelf.items].sort((a, b) => a[1] - b[1]);
  let n = 0;
  for (const [, cost] of sorted) { if (cost <= purse) { purse -= cost; n++; } }
  return n;
}

const results = Object.fromEntries(Object.keys(PROFILES).map(k => [k, runProfile(k)]));

// ---- the report ----------------------------------------------------------------------
const L = [];
const A = s => L.push(s);
A('# RUN15 V5 — the balance simulation');
A('');
A('Generated by `tests/lib/run15_balance.mjs`. Thirty simulated days per profile against');
A("the REAL award machinery (`spendableAward` in js/comfort.js, the mapping in");
A('data/startypes.js) and the REAL price table (data/shop.js). Nothing here is estimated.');
A('');
A('Every profile starts with the Welcome purse of ' + WELCOME_PURSE + ' legacy stars.');
A('');
for (const [key, p] of Object.entries(PROFILES)) {
  A(`## ${p.label}`);
  A('');
  A(`_${p.note}_`);
  A('');
  A('| day | maths | word | puzzle | creative | lesson | legacy |');
  A('|---:|---:|---:|---:|---:|---:|---:|');
  for (const d of [7, 14, 30]) {
    const w = results[key][d];
    A(`| ${d} | ${w.maths} | ${w.word} | ${w.puzzle} | ${w.creative} | ${w.lesson} | ${w.legacy} |`);
  }
  A('');
  A('| day | House | Town | Playground | Wearables | Special |');
  A('|---:|---|---|---|---|---|');
  for (const d of [7, 14, 30]) {
    const a = affordability(results[key][d]);
    const cell = (id) => `${a[id].count}/${a[id].of}${a[id].count ? ` (buys ${basket(results[key][d], id)})` : ''}`;
    A(`| ${d} | ${cell('house')} | ${cell('town')} | ${cell('playground')} | ${cell('wearables')} | ${cell('special')} |`);
  }
  A('');
  A('_"3/20 (buys 2)" = three items are individually affordable, and spending cheapest-first she can take home two._');
  A('');
}

// ---- the targets, checked ------------------------------------------------------------
A('## The authored targets, checked');
A('');
const day1 = Object.fromEntries([...TYPE_KEYS, 'legacy'].map(k => [k, 0]));
day1.legacy = WELCOME_PURSE;
const d1 = affordability(day1);
const day1Count = Object.values(d1).reduce((n, x) => n + x.count, 0);
const rows = [];
rows.push(['A new player can afford at least six items on day one', day1Count >= 6, `${day1Count} affordable with the Welcome purse alone`]);
const f14 = affordability(results.farmer[14]);
rows.push(['A maths-only farmer at day 14 can furnish a room and buy several town items',
  f14.town.count >= 5, `Town ${f14.town.count}/${f14.town.of}, buys ${basket(results.farmer[14], 'town')}`]);
rows.push(['…but cannot reach the Special shelf at all', f14.special.count === 0, `Special ${f14.special.count}/${f14.special.of} (lesson purse ${results.farmer[14].lesson})`]);
const b14 = affordability(results.broad[14]);
rows.push(['A broad player at day 14 can afford something from every shelf including one Special',
  Object.values(b14).every(x => x.count >= 1), Object.entries(b14).map(([k, v]) => `${k} ${v.count}`).join(', ')]);
const l14 = affordability(results.lessons[14]);
rows.push(['A lesson-keen player reaches the Special shelf fastest (and within a fortnight)',
  l14.special.count >= 1, `Special ${l14.special.count}/${l14.special.of} by day 14 (lesson purse ${results.lessons[14].lesson})`]);
// nobody locked out of every shelf for more than three days of ordinary play
let worstLockout = 0;
for (const key of Object.keys(PROFILES)) {
  const wallet = Object.fromEntries([...TYPE_KEYS, 'legacy'].map(k => [k, 0]));
  wallet.legacy = WELCOME_PURSE;
  let lockedRun = 0;
  let lessonsDone = 0;
  for (let d = 1; d <= 30; d++) {
    for (const r of PROFILES[key].day(d)) {
      let stars = r.stars;
      if (r.game === 'teachme') { lessonsDone++; if (lessonsDone > RECAP_AFTER) stars = RECAP_STARS; }
      wallet[starTypeFor(r.game, r.cat)] += spendableAward({ stars, level: r.level, above: r.above }).spendable;
    }
    const a = affordability(wallet);
    const anything = Object.values(a).some(x => x.count > 0);
    lockedRun = anything ? 0 : lockedRun + 1;
    worstLockout = Math.max(worstLockout, lockedRun);
  }
}
rows.push(['Nobody is locked out of every shelf for more than three days', worstLockout <= 3, `worst run: ${worstLockout} day(s)`]);
A('| target | met | evidence |');
A('|---|:--:|---|');
for (const [t, met, ev] of rows) A(`| ${t} | ${met ? '✅' : '❌'} | ${ev} |`);
A('');
const allMet = rows.every(r => r[1]);
A(allMet
  ? '**Every authored target is met by the shipped prices** (the Special shelf was tuned from'
    + ' the draft 20/24/28 to 24/28/32 — see the comment in data/shop.js; every other number is'
    + ' the authored draft, unchanged).'
  : '**Some targets are unmet — the prices above need another pass.**');
A('');
A('## The price table as shipped');
A('');
for (const shelf of SHELVES) {
  A(`**${shelf.label}** — ${shelf.currency} stars. ${shelf.blurb}`);
  A('');
  A(shelf.items.map(([id, cost]) => `${id.replace(/^(deco|acc)_/, '')} ${cost}`).join(' · '));
  A('');
}
writeFileSync('tests/run15_balance.md', L.join('\n'));
console.log(L.slice(L.indexOf('## The authored targets, checked')).join('\n'));
console.log('\nwrote tests/run15_balance.md');
process.exit(allMet ? 0 : 1);
